# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menugestion.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from qgis.PyQt import QtCore, QtGui, QtWidgets

class Ui_Catastro(object):
    def setupUi(self, Catastro):
        Catastro.setObjectName("Catastro")
        Catastro.resize(290, 130)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon_respaldos32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Catastro.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Catastro)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        Catastro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Catastro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 290, 21))
        self.menubar.setObjectName("menubar")
        self.menuinicio = QtWidgets.QMenu(self.menubar)
        self.menuinicio.setObjectName("menuinicio")
        self.menuPredios = QtWidgets.QMenu(self.menubar)
        self.menuPredios.setObjectName("menuPredios")
        self.menuBusqueda = QtWidgets.QMenu(self.menubar)
        self.menuBusqueda.setObjectName("menuBusqueda")
        Catastro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Catastro)
        self.statusbar.setObjectName("statusbar")
        Catastro.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Catastro)
        self.toolBar.setObjectName("toolBar")
        Catastro.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actioniniciar_sesios = QtWidgets.QAction(Catastro)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/icon_usuarios64x64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioniniciar_sesios.setIcon(icon1)
        self.actioniniciar_sesios.setObjectName("actioniniciar_sesios")
        self.actionCerrar_sesi_n = QtWidgets.QAction(Catastro)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/icon_cancelar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerrar_sesi_n.setIcon(icon2)
        self.actionCerrar_sesi_n.setObjectName("actionCerrar_sesi_n")
        self.actionMovimientos = QtWidgets.QAction(Catastro)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/icon_rptmovimientos32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMovimientos.setIcon(icon3)
        self.actionMovimientos.setObjectName("actionMovimientos")
        self.actionValor_unitario = QtWidgets.QAction(Catastro)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/icon_movimientos32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionValor_unitario.setIcon(icon4)
        self.actionValor_unitario.setObjectName("actionValor_unitario")
        self.actionBuscar = QtWidgets.QAction(Catastro)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/icon_buscar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuscar.setIcon(icon5)
        self.actionBuscar.setObjectName("actionBuscar")
        self.menuinicio.addAction(self.actioniniciar_sesios)
        self.menuinicio.addAction(self.actionCerrar_sesi_n)
        self.menuPredios.addAction(self.actionValor_unitario)
        self.menuPredios.addAction(self.actionMovimientos)
        self.menuBusqueda.addAction(self.actionBuscar)
        self.menubar.addAction(self.menuinicio.menuAction())
        self.menubar.addAction(self.menuBusqueda.menuAction())
        self.menubar.addAction(self.menuPredios.menuAction())
        self.toolBar.addAction(self.actioniniciar_sesios)
        self.toolBar.addAction(self.actionMovimientos)
        self.toolBar.addAction(self.actionValor_unitario)
        self.toolBar.addAction(self.actionBuscar)
        self.toolBar.addAction(self.actionCerrar_sesi_n)

        self.retranslateUi(Catastro)
        self.menubar.triggered['QAction*'].connect(self.lineEdit.clear)
        self.toolBar.actionTriggered['QAction*'].connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Catastro)

    def retranslateUi(self, Catastro):
        _translate = QtCore.QCoreApplication.translate
        Catastro.setWindowTitle(_translate("Catastro", "Catastro"))
        self.menuinicio.setTitle(_translate("Catastro", "Inicio"))
        self.menuPredios.setTitle(_translate("Catastro", "Predios"))
        self.menuBusqueda.setTitle(_translate("Catastro", "Busqueda"))
        self.toolBar.setWindowTitle(_translate("Catastro", "toolBar"))
        self.actioniniciar_sesios.setText(_translate("Catastro", "Usuarios"))
        self.actionCerrar_sesi_n.setText(_translate("Catastro", "Cerrar"))
        self.actionMovimientos.setText(_translate("Catastro", "Tramites"))
        self.actionValor_unitario.setText(_translate("Catastro", "Valor unitario"))
        self.actionBuscar.setText(_translate("Catastro", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Catastro = QtWidgets.QMainWindow()
    ui = Ui_Catastro()
    ui.setupUi(Catastro)
    Catastro.show()
    sys.exit(app.exec_())
